name: ci
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Python environment for Frappe
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Setup Python environment for Flask
      - name: Set up Python for Flask
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Install dependencies for Flask
      - name: Install Flask Dependencies
        run: pip install -r requirements.txt
